In [ ]:
dataset1 = {
    "Name": ["Edward Teach", "Anne Bonny", "John Rackham", "Cheung Po Tsai", "Grace O'Malley", "Mary Read", "Sayyida al Hurra", "Zheng Yi Sao", "Francis Drake", "Jean Lafitte"],
    "Years Active": ["1716 - 1718", "1718 - 1720", "1718 - 1720", "1798 - 1810", "1564 - 1595", "1708 - 1721", "1515 - 1545", "1801 - 1810", "1563 - 1596", "1810 - 1823"],
    "Sailed": ["Caribbean", "Caribbean", "Caribbean", "South China Sea", "British Isles", "Caribbean", "Mediterranean", "South China Sea", "Caribbean", "Gulf of Mexico"],
    "Alias": ["Blackbeard", "", "Calico Jack", "The Kid", "Queen of Ireland", "Mark", "Hakimat Titwan", "Ching Shih", "Sir Francis Drake", "Terror of the Gulf"]
}

In [ ]:
dataset2 = {
    "Edward Teach": {
        "Years Active": ["1716 - 1718"],
        "Sailed": ["Caribbean"],
        "Alias": ["Blackbeard"]
    },

    "Anne Bonny": {
        "Years Active": ["1718 - 1720"],
        "Sailed": ["Caribbean"],
        "Alias": [""]
    },

    "John Rackham": {
        "Years Active": ["1718 - 1720"],
        "Sailed": ["Caribbean"],
        "Alias": ["Calico Jack"]
    },

    "Cheung Po Tsai": {
        "Years Active": ["1798 - 1810"],
        "Sailed": ["South China Sea"],
        "Alias": ["The Kid"]
    },

    "Grace O'Malley": {
        "Years Active": ["1564 - 1595"],
        "Sailed": ["British Isles"],
        "Alias": ["Queen of Ireland"]
    },

    "Mary Read": {
        "Years Active": ["1708 - 1721"],
        "Sailed": ["Caribbean"],
        "Alias": ["Mark"]
    },

    "Sayyida al Hurra": {
        "Years Active": ["1515 - 1545"],
        "Sailed": ["Mediterranean"],
        "Alias": ["Hakimat Titwan"]
    },

    "Zheng Yi Sao": {
        "Years Active": ["1801 - 1810"],
        "Sailed": ["South China Sea"],
        "Alias": ["Ching Shih"]
    },

    "Francis Drake": {
        "Years Active": ["1563 - 1596"],
        "Sailed": ["Caribbean"],
        "Alias": ["Sir Francis Drake"]
    },

    "Jean Lafitte": {
        "Years Active": ["1810 - 1823"],
        "Sailed": ["Gulf of Mexico"],
        "Alias": ["Terror of the Gulf"]
    },
}